# Site specific settings
title: "LameLemon"
name: "LameLemon"
keywords: "programmer, computer network, technician, software engineer"
url: "https://lamelemon.github.io"
baseurl: ""
description: "A Developer and Network Technician and Arduino enthusiast"
cover: ""
fanpage_id: ""

# Site general settings
lang: "en"
ssl: false # It will redirect to https
plugins_dir:
  - jekyll-redirect-from

# Media
disqus:
twitter: helep0d
github: LameLemon

# Build settings
markdown: kramdown
permalink: /:categories/:title/
